spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deliveries_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true